### ISSUE TITLE
Some details problem

### ISSUE THREAD

**Issue by rhett-chen** [isacarnekvist/open-ai-yumi#2]
Hi, thanks for your great work! I recently use mujoco to simulate Yumi Robot, but I met a problem when I used the mujoco compile file to covert the yumi.urdf to yumi.xml.  The yumi.xml file I got doesn't contain the **actuator** part and also the **ctrlrange**,  so I wonder how you got this part in your open-ai-yumi/gym/envs/mujoco/yumi/yumi.xml.  I sincerely hope you can give me some instructions, thanks.

**Comment by v-wewei** [comment]
hi, @rhett-chen  did you solve the problem? Thanks.
